# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: postgres-db
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro